### ISSUE TITLE
Unhandled Exception: NtApiDotNet.NtException: (0x8000000D) - {Partial Copy}

### ISSUE THREAD

**Issue by duzvik** [CCob/BeaconEye#5]
Any ideas on how to fix this?
It's an x86 version from releases.

```
[+] Scanning for beacon processess...
NotSpecified: (:String) [], RemoteException
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
    + PSComputerName        : pc

Unhandled Exception: NtApiDotNet.NtException: (0x8000000D) - {Partial Copy}
Due to protection conflicts not all the requested bytes could be copied.
   at NtApiDotNet.NtObjectUtils.ToNtException(NtStatus status, Boolean throw_on_error)
   at NtApiDotNet.NtVirtualMemory.ReadMemory[T](SafeKernelObjectHandle process, Int64 base_address)
   at BeaconEye.NtProcessReader.ReadMemory[T](UInt64 address)
   at BeaconEye.ProcessReader.get_Heaps()
   at BeaconEye.BeaconEye.ProcessHasConfig(ProcessReader process)
   at BeaconEye.BeaconEye.IsBeaconProcess(ProcessReader process, Boolean monitor)
   at BeaconEye.BeaconEye.Main(String[] args)
```

**Comment by mbmy** [comment]
Just started testing this and encountered the same with x64 when executed from a SYSTEM process.
